"""Built-in declarative plugin-profile seed data."""

from __future__ import annotations

from fl_mcp.schemas.plugin_profiles import (
    PluginControl,
    PluginControlRisk,
    PluginFormat,
    PluginKind,
    PluginProfile,
    PluginProfileStatus,
    PluginSupportPriority,
    PluginValueMap,
    PluginValueMapKind,
)

SOURCE_FL_MIDI = (
    "https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/midi_scripting.htm"
)
SOURCE_VST3 = "https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical%2BDocumentation/Parameters%2BAutomation/Index.html"
SOURCE_FABFILTER_PRO_Q3 = "https://www.fabfilter.com/help/ffproq3-manual.pdf"
SOURCE_SYLENTH1 = "https://www.lennardigital.com/files/Sylenth1Manual.pdf"
SOURCE_IZOTOPE_MANUALS = "https://support.izotope.com/hc/en-us/articles/8848064901277-iZotope-Product-Manuals-Documentation"
SOURCE_CABLEGUYS = "https://www.cableguys.com/support/audio-automation-midi-and-timing"
SOURCE_FL_STOCK = (
    "https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins.htm"
)


def _control(
    control_id: str,
    label: str,
    *,
    group: str = "main",
    unit: str | None = None,
    value_map: PluginValueMapKind = "normalized",
    min_value: float | None = None,
    max_value: float | None = None,
    midi_cc: int | None = None,
    requires_window: bool = False,
    requires_midi: bool = False,
    risk: PluginControlRisk = "safe",
) -> PluginControl:
    return PluginControl(
        control_id=control_id,
        label=label,
        group=group,
        unit=unit,
        value_map=PluginValueMap(kind=value_map, min_value=min_value, max_value=max_value),
        parameter_name_hint=label,
        midi_cc=midi_cc,
        requires_window=requires_window,
        requires_midi=requires_midi,
        risk=risk,
    )


def _stub(
    profile_id: str,
    display_name: str,
    *,
    vendor: str | None,
    family: str,
    aliases: list[str],
    kind: PluginKind,
    formats: list[PluginFormat],
    status: PluginProfileStatus = "stub",
    priority: PluginSupportPriority = "P3_inventory_only_on_demand",
    provenance: list[str] | None = None,
) -> PluginProfile:
    return PluginProfile(
        profile_id=profile_id,
        vendor=vendor,
        family=family,
        display_name=display_name,
        aliases=aliases,
        kind=kind,
        supported_formats=formats,
        semantic_controls=[],
        support_priority=priority,
        provenance=provenance or [SOURCE_FL_MIDI, SOURCE_VST3],
        confidence=0.2 if status == "stub" else 0.1,
        status=status,
    )


def seed_profiles() -> tuple[PluginProfile, ...]:
    """Return deterministic built-in plugin-profile seeds.

    These profiles intentionally provide semantic control names only. Concrete
    FL wrapper parameter indices are supplied by local calibrations or curated
    verified profile data, not by vendor MIDI manuals.
    """

    return (
        PluginProfile(
            profile_id="lennardigital.sylenth1",
            vendor="LennarDigital",
            family="Sylenth1",
            display_name="Sylenth1",
            aliases=["Sylenth1", "Sylenth 1", "LennarDigital Sylenth1"],
            kind="instrument",
            supported_formats=["au", "vst", "vst3"],
            preset_loaders=["fxp", "fxb", "fst"],
            semantic_controls=[
                _control(
                    "main.volume", "Main Volume", group="main", value_map="percent", midi_cc=7
                ),
                _control("mix.a", "Mix A", group="mixer", value_map="percent", midi_cc=8),
                _control("mix.b", "Mix B", group="mixer", value_map="percent", midi_cc=9),
                _control(
                    "filter_a.cutoff",
                    "Filter A Cutoff",
                    group="filter",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                    midi_cc=72,
                ),
                _control(
                    "filter_b.cutoff",
                    "Filter B Cutoff",
                    group="filter",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                    midi_cc=73,
                ),
                _control(
                    "filter.cutoff",
                    "Filter Ctrl Cutoff",
                    group="filter",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                    midi_cc=74,
                ),
                _control(
                    "filter.resonance",
                    "Filter Ctrl Resonance",
                    group="filter",
                    value_map="percent",
                    midi_cc=71,
                ),
                _control("amp_env_a.attack", "AmpEnv A Attack", group="envelope", midi_cc=76),
                _control("amp_env_a.decay", "AmpEnv A Decay", group="envelope", midi_cc=77),
                _control("amp_env_a.sustain", "AmpEnv A Sustain", group="envelope", midi_cc=78),
                _control("amp_env_a.release", "AmpEnv A Release", group="envelope", midi_cc=79),
                _control("lfo_1.rate", "LFO 1 Rate", group="lfo", midi_cc=84),
                _control("lfo_1.gain", "LFO 1 Gain", group="lfo", midi_cc=85),
                _control("osc_a1.detune", "Osc A1 Detune", group="oscillator", midi_cc=12),
                _control("osc_a2.detune", "Osc A2 Detune", group="oscillator", midi_cc=17),
                _control("distortion.amount", "Distortion Amount", group="fx", risk="creative"),
            ],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_SYLENTH1],
            support_priority="P0_paid_installed",
            confidence=0.55,
            status="seed",
        ),
        PluginProfile(
            profile_id="xfer.serum2",
            vendor="Xfer Records",
            family="Serum",
            display_name="Serum 2",
            aliases=["Serum2", "Serum 2", "Xfer Serum 2", "Serum"],
            kind="instrument",
            supported_formats=["au", "vst3"],
            semantic_controls=[
                _control("macro_1", "Macro 1", group="macros"),
                _control("macro_2", "Macro 2", group="macros"),
                _control("macro_3", "Macro 3", group="macros"),
                _control("macro_4", "Macro 4", group="macros"),
                _control(
                    "filter.cutoff",
                    "Filter Cutoff",
                    group="filter",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                ),
                _control("filter.resonance", "Filter Resonance", group="filter"),
                _control("env_1.attack", "Envelope 1 Attack", group="envelope"),
                _control("lfo_1.rate", "LFO 1 Rate", group="lfo"),
            ],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3],
            support_priority="P0_paid_installed",
            confidence=0.35,
            status="seed",
        ),
        PluginProfile(
            profile_id="xfer.serum2_fx",
            vendor="Xfer Records",
            family="Serum",
            display_name="Serum 2 FX",
            aliases=["Serum 2 FX", "Serum2 FX", "Serum FX"],
            kind="effect",
            supported_formats=["vst3"],
            semantic_controls=[
                _control("macro_1", "Macro 1", group="macros"),
                _control("filter.cutoff", "Filter Cutoff", group="filter"),
                _control("fx.mix", "FX Mix", group="fx"),
            ],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3],
            support_priority="P0_paid_installed",
            confidence=0.3,
            status="seed",
        ),
        PluginProfile(
            profile_id="fabfilter.pro_q3",
            vendor="FabFilter",
            family="Pro-Q",
            display_name="FabFilter Pro-Q 3",
            aliases=["FabFilter Pro-Q 3", "Pro-Q 3", "Pro Q 3"],
            kind="effect",
            supported_formats=["au", "vst", "vst3", "clap"],
            semantic_controls=[
                _control(
                    "output.gain",
                    "Output Gain",
                    group="output",
                    unit="db",
                    value_map="db",
                    min_value=-30,
                    max_value=30,
                ),
                _control("gain_scale", "Gain Scale", group="output", value_map="percent"),
                _control(
                    "band_1.frequency",
                    "Band 1 Frequency",
                    group="band_1",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                ),
                _control(
                    "band_1.gain",
                    "Band 1 Gain",
                    group="band_1",
                    unit="db",
                    value_map="db",
                    min_value=-30,
                    max_value=30,
                ),
                _control(
                    "band_1.q",
                    "Band 1 Q",
                    group="band_1",
                    value_map="linear",
                    min_value=0.025,
                    max_value=40,
                ),
                _control(
                    "active_band.frequency",
                    "Active Band Frequency",
                    group="active_band",
                    requires_window=True,
                ),
                _control(
                    "active_band.gain",
                    "Active Band Gain",
                    group="active_band",
                    unit="db",
                    value_map="db",
                    min_value=-30,
                    max_value=30,
                    requires_window=True,
                ),
            ],
            routing_requirements=["active_band controls require the plugin window to be open"],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FABFILTER_PRO_Q3],
            support_priority="P0_paid_installed",
            confidence=0.5,
            status="seed",
        ),
        PluginProfile(
            profile_id="fabfilter.pro_c2",
            vendor="FabFilter",
            family="Pro-C",
            display_name="FabFilter Pro-C 2",
            aliases=["FabFilter Pro-C 2", "FabFilter Pro-C 2 (Mono)", "Pro-C 2", "Pro C 2"],
            kind="effect",
            supported_formats=["au", "vst", "vst3", "clap"],
            semantic_controls=[
                _control(
                    "threshold",
                    "Threshold",
                    group="compressor",
                    unit="db",
                    value_map="db",
                    min_value=-60,
                    max_value=0,
                ),
                _control(
                    "ratio",
                    "Ratio",
                    group="compressor",
                    value_map="linear",
                    min_value=1,
                    max_value=100,
                ),
                _control(
                    "attack",
                    "Attack",
                    group="compressor",
                    unit="ms",
                    value_map="milliseconds",
                    min_value=0.005,
                    max_value=250,
                ),
                _control(
                    "release",
                    "Release",
                    group="compressor",
                    unit="ms",
                    value_map="milliseconds",
                    min_value=5,
                    max_value=5000,
                ),
                _control("knee", "Knee", group="compressor"),
                _control("mix", "Mix", group="output", value_map="percent"),
                _control(
                    "output.gain",
                    "Output Gain",
                    group="output",
                    unit="db",
                    value_map="db",
                    min_value=-36,
                    max_value=36,
                ),
            ],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3],
            support_priority="P0_paid_installed",
            confidence=0.45,
            status="seed",
        ),
        PluginProfile(
            profile_id="cableguys.shaperbox2",
            vendor="Cableguys",
            family="ShaperBox",
            display_name="ShaperBox 2",
            aliases=["ShaperBox 2", "Cableguys ShaperBox 2"],
            kind="effect",
            supported_formats=["au", "vst", "vst3"],
            semantic_controls=[
                _control(
                    "volume.mix",
                    "VolumeShaper Mix",
                    group="volume",
                    value_map="percent",
                    risk="creative",
                ),
                _control(
                    "filter.cutoff",
                    "FilterShaper Cutoff",
                    group="filter",
                    unit="hz",
                    value_map="log_frequency",
                    min_value=20,
                    max_value=20000,
                ),
                _control(
                    "drive.mix",
                    "DriveShaper Mix",
                    group="drive",
                    value_map="percent",
                    risk="creative",
                ),
                _control(
                    "midi_trigger",
                    "MIDI Trigger",
                    group="routing",
                    requires_midi=True,
                    risk="volatile",
                ),
            ],
            routing_requirements=["MIDI-triggered LFO behavior requires routed MIDI notes"],
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_CABLEGUYS],
            support_priority="P0_paid_installed",
            confidence=0.35,
            status="seed",
        ),
        _stub(
            "fabfilter.micro",
            "FabFilter Micro",
            vendor="FabFilter",
            family="Micro",
            aliases=["FabFilter Micro", "Micro"],
            kind="effect",
            formats=["au", "vst"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.pro_ds",
            "FabFilter Pro-DS",
            vendor="FabFilter",
            family="Pro-DS",
            aliases=["FabFilter Pro-DS", "Pro-DS"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.pro_g",
            "FabFilter Pro-G",
            vendor="FabFilter",
            family="Pro-G",
            aliases=["FabFilter Pro-G", "Pro-G"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.pro_l2",
            "FabFilter Pro-L 2",
            vendor="FabFilter",
            family="Pro-L",
            aliases=["FabFilter Pro-L 2", "Pro-L 2"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.pro_mb",
            "FabFilter Pro-MB",
            vendor="FabFilter",
            family="Pro-MB",
            aliases=["FabFilter Pro-MB", "Pro-MB"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.pro_r",
            "FabFilter Pro-R",
            vendor="FabFilter",
            family="Pro-R",
            aliases=["FabFilter Pro-R", "Pro-R"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.saturn2",
            "FabFilter Saturn 2",
            vendor="FabFilter",
            family="Saturn",
            aliases=["FabFilter Saturn 2", "Saturn 2"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.simplon",
            "FabFilter Simplon",
            vendor="FabFilter",
            family="Simplon",
            aliases=["FabFilter Simplon", "Simplon"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.timeless3",
            "FabFilter Timeless 3",
            vendor="FabFilter",
            family="Timeless",
            aliases=["FabFilter Timeless 3", "Timeless 3"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.volcano3",
            "FabFilter Volcano 3",
            vendor="FabFilter",
            family="Volcano",
            aliases=["FabFilter Volcano 3", "Volcano 3"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.one",
            "FabFilter One",
            vendor="FabFilter",
            family="One",
            aliases=["FabFilter One", "One"],
            kind="instrument",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "fabfilter.twin3",
            "FabFilter Twin 3",
            vendor="FabFilter",
            family="Twin",
            aliases=["FabFilter Twin 3", "Twin 3"],
            kind="instrument",
            formats=["au", "vst", "vst3"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "camel_audio.camelcrusher",
            "CamelCrusher",
            vendor="Camel Audio",
            family="CamelCrusher",
            aliases=["CamelCrusher", "Camel Crusher"],
            kind="effect",
            formats=["vst", "fst"],
            priority="P2_popular_useful_stock_or_free",
        ),
        _stub(
            "d16.drumazon",
            "Drumazon",
            vendor="D16 Group",
            family="Drumazon",
            aliases=["Drumazon", "D16 Drumazon"],
            kind="instrument",
            formats=["vst", "fst"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "valhalla.valhallaroom",
            "ValhallaRoom",
            vendor="Valhalla DSP",
            family="ValhallaRoom",
            aliases=["ValhallaRoom", "Valhalla Room"],
            kind="effect",
            formats=["fst"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "image_line.fl_studio_vst",
            "FL Studio VSTi",
            vendor="Image-Line",
            family="FL Studio",
            aliases=["FL Studio VSTi", "FL Studio"],
            kind="instrument",
            formats=["au", "vst"],
            priority="P1_paid_detected_or_suite",
        ),
        _stub(
            "image_line.fruity_parametric_eq_2",
            "Fruity Parametric EQ 2",
            vendor="Image-Line",
            family="Fruity Parametric EQ",
            aliases=["Fruity Parametric EQ 2", "Parametric EQ 2", "PEQ2"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.fruity_limiter",
            "Fruity Limiter",
            vendor="Image-Line",
            family="Fruity Limiter",
            aliases=["Fruity Limiter", "Limiter"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.maximus",
            "Maximus",
            vendor="Image-Line",
            family="Maximus",
            aliases=["Maximus"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.gross_beat",
            "Gross Beat",
            vendor="Image-Line",
            family="Gross Beat",
            aliases=["Gross Beat", "Grossbeat"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.flex",
            "FLEX",
            vendor="Image-Line",
            family="FLEX",
            aliases=["FLEX", "Flex"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.fpc",
            "FPC",
            vendor="Image-Line",
            family="FPC",
            aliases=["FPC"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.directwave",
            "DirectWave",
            vendor="Image-Line",
            family="DirectWave",
            aliases=["DirectWave"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.edison",
            "Edison",
            vendor="Image-Line",
            family="Edison",
            aliases=["Edison"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.slicex",
            "Slicex",
            vendor="Image-Line",
            family="Slicex",
            aliases=["Slicex", "SliceX"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.sytrus",
            "Sytrus",
            vendor="Image-Line",
            family="Sytrus",
            aliases=["Sytrus"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.harmor",
            "Harmor",
            vendor="Image-Line",
            family="Harmor",
            aliases=["Harmor"],
            kind="instrument",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.patcher",
            "Patcher",
            vendor="Image-Line",
            family="Patcher",
            aliases=["Patcher"],
            kind="instrument_or_effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.fruity_reeverb_2",
            "Fruity Reeverb 2",
            vendor="Image-Line",
            family="Fruity Reeverb",
            aliases=["Fruity Reeverb 2", "Reeverb 2", "Fruity Reverb 2"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.fruity_delay_3",
            "Fruity Delay 3",
            vendor="Image-Line",
            family="Fruity Delay",
            aliases=["Fruity Delay 3", "Delay 3"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.fruity_soft_clipper",
            "Fruity Soft Clipper",
            vendor="Image-Line",
            family="Fruity Soft Clipper",
            aliases=["Fruity Soft Clipper", "Soft Clipper"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "image_line.wave_candy",
            "Wave Candy",
            vendor="Image-Line",
            family="Wave Candy",
            aliases=["Wave Candy"],
            kind="effect",
            formats=["fst"],
            priority="P2_popular_useful_stock_or_free",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_FL_STOCK],
        ),
        _stub(
            "izotope.trash",
            "iZotope Trash",
            vendor="iZotope",
            family="Trash",
            aliases=["iZotope Trash", "Trash", "Trash 2", "Trash 2024"],
            kind="effect",
            formats=["au", "vst", "vst3"],
            status="desired",
            priority="desired_not_installed",
            provenance=[SOURCE_FL_MIDI, SOURCE_VST3, SOURCE_IZOTOPE_MANUALS],
        ),
    )
