name: Docs Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'
      - '!v*.*.*rc*'
      - '!v*.*.*alpha*'
      - '!v*.*.*beta*'

concurrency:
  group: docs-deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: none

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@9fd676a19091d4595eefd76e4bd31c97133911f1 # v4.2.0
        with:
          version: '9.15.4'
      - name: Install dependencies
        run: pnpm --dir docs install --frozen-lockfile
      - name: Build static docs
        run: pnpm --dir docs build
      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: docs/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
